package com.lifetech.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-02-08T01:46:19.551+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://service.lifetech.com/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebResult(name = "PiyushMessageToWorld", targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://service.lifetech.com/", className = "com.lifetech.service.GetMessage")
    @WebMethod
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://service.lifetech.com/", className = "com.lifetech.service.GetMessageResponse")
    public java.lang.String getMessage(
        @WebParam(name = "CurrentName", targetNamespace = "")
        java.lang.String currentName
    );
}
