
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lifetech.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-02-08T01:46:19.542+05:30
 * Generated source version: 2.7.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "helloService",
                      portName = "helloPort",
                      targetNamespace = "http://service.lifetech.com/",
                      wsdlLocation = "http://localhost:8085/SoapService/hello?wsdl",
                      endpointInterface = "com.lifetech.service.HelloWorldService")
                      
public class HelloWorldServiceImpl implements HelloWorldService {

    private static final Logger LOG = Logger.getLogger(HelloWorldServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.lifetech.service.HelloWorldService#getMessage(java.lang.String  currentName )*
     */
    public java.lang.String getMessage(java.lang.String currentName) { 
        LOG.info("Executing operation getMessage");
        System.out.println(currentName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
